name: Main
on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: "[Setup] repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "[Setup] Go"
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: "[Setup] svu"
        run: go install github.com/caarlos0/svu@latest

      - name: "[CD] release"
        run: |
          [ "$(svu current | cut -f2 -d.)" != "$(date +%-m)" ] && gh release create v$(date +%Y.%-m.0) || gh release create "$(svu patch)"
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
